language: python
cache: pip
python:
  - "3.4"
  - "3.5"
  - "3.6"

- install:
  - pip install .[dev]
- script:
  - cd tests
  - py.test

jobs:
  include:
    - stage: compliance
      script: pre-commit run --all-files

stages:
  - test
  - compliance
