language: python
cache: pip
python:
  - "3.4"
  - "3.5"
  - "3.6"

install:
  - pip install .[dev]

jobs:
  include:
    - script:
      - cd tests
      - py.test
    - stage: compliance
      python: 3.6
      script: pre-commit run --all-files
