language: python
cache: pip
python:
  - "3.4"
  - "3.5"
  - "3.6"

install:
  - pip install .[dev]

jobs:
  include:
    - stage: compliance
      script: pre-commit run --all-files
    - stage: test
      script:
        - cd tests
        - py.test
