language: python
cache: pip
python:
  - "3.4"
  - "3.5"
  - "3.6"

jobs:
  include:
    - install:
      - pip install .[dev]
      script:
      - cd tests
      - py.test
    - stage: compliance
      script: pre-commit run --all-files
