name: Continuous Integration

on: [pull_request]

_anchors:
  checkout: &CHECKOUT
    name: Checkout code
    uses: actions/checkout@v3

  pip-cache: &PIP_CACHE
    uses: actions/cache@v3
    with:
      path: ~/.cache/pip
      key: pip-${{ matrix.python-version }}-${{ matrix.install-type }}-${{ hashFiles('**/poetry.lock') }}
      restore-keys: pip-${{ matrix.python-version }}-${{ matrix.install-type }}

  python-setup: &PYTHON_SETUP
    name: Set up Python
    uses: actions/setup-python@v4
    with:
      python-version: ${{ matrix.python-version }}

  install-project: &INSTALL_PROJECT
    name: Install the python project
    env:
      INSTALL_TYPE: ${{ matrix.install-type }}
    run: .ci/install_script.sh

jobs:
  docs:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.8]
        install-type: [dev]
    steps:
      - *CHECKOUT
      - *PIP_CACHE
      - *PYTHON_SETUP
      - *INSTALL_PROJECT
      - name: Build documentation
        run: poetry run make SPHINXOPTS='-nW' -C doc html
      - uses: actions/upload-artifact@v3
        with:
          name: doc-build
          path: doc/build/html

  pre-commit:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.8]
        install-type: [dev]
    steps:
      - *CHECKOUT
      - *PIP_CACHE
      - *PYTHON_SETUP
      - *INSTALL_PROJECT
      - name: Run pre-commit
        run: poetry run pre-commit run --all-files || ( git status --short ; git diff ; exit 1 )
  tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.8", "3.9", "3.10", "3.11"]
        install-type: [dev]
        include:
          - python-version: 3.8
            install-type: dev_sdist
          - python-version: 3.8
            install-type: dev_bdist_wheel
    steps:
      - *CHECKOUT
      - *PIP_CACHE
      - *PYTHON_SETUP
      - *INSTALL_PROJECT
      - name: Run pytest
        run: poetry run pytest --cov=bands_inspect --cov-config=.coveragerc
        if: matrix.install-type == 'dev'
      - name: Run pytest
        run: pytest --cov=bands_inspect --cov-config=.coveragerc
        if: matrix.install-type != 'dev'
      - name: Run codecov
        run: codecov
